#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  pkg ensure devel/jq
}

function old_bootstrap {
  local url_jq
  
  case "$(uname -s)" in
    Darwin) url_jq='https://github.com/stedolan/jq/releases/download/jq-1.5/jq-osx-amd64' ;;
    *)      url_jq='https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64' ;;
  esac

  local tmp_jq="$(mktemp -t XXXXXX)"
  trap "$(printf "rm -f '%q'" "$tmp_jq")" EXIT
  curl -sS -L -o "$tmp_jq" "$url_jq"
  chmod 755 "$tmp_jq"
  mv -f "$tmp_jq" "$shome/bin/jq.tmp"
  mv -f "$shome/bin/jq.tmp" "$shome/bin/jq"

  block compile virtualenv
}

bootstrap
