#!/usr/bin/env bash

function main {
  local shome="${_jq_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  if [[ -x "$shome/bin/jq" ]]; then
    return 1
  else
    return 0
  fi
}

source sub "$0" "$@"
