#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_jq="$(jq --version 2>/dev/null | cut -d- -f2 || true)"
  jq -n --arg jq "$ver_jq" '{jq: $jq}'
}

version "$@"
